parameters:
  - name: CONTINUE_ON_VALIDATION_ERROR_IN_DEVELOPMENT
    displayName: Continue on validation error (just in development)
    type: boolean
    default: False
    values:
      - False
      - True
  - name: ENVIRONMENT
    displayName: Environment
    type: string
    default: default
    values:
      - dev
      - qa
      - prod
      - default
  - name: FLOW_TYPE
    displayName: Flow
    type: string
    default: Full
    values:
      - Express
      - Full

trigger:
  branches:
    include:
      - master
      - release/*

resources:
  repositories:
    - repository: deuna-tpl-do-pipeline-microservice
      type: git
      name: cpr-devops/deuna-tpl-do-pipeline-microservice
      ref: refs/tags/v12.4.1

extends:
  template: javascript/nestjs/npm/ci.yml@deuna-tpl-do-pipeline-microservice
  parameters:
    CONTINUE_ON_VALIDATION_ERROR_IN_DEVELOPMENT: ${{ parameters.CONTINUE_ON_VALIDATION_ERROR_IN_DEVELOPMENT }}
    ENVIRONMENT: ${{ parameters.ENVIRONMENT }}
    FLOW_TYPE: ${{ parameters.FLOW_TYPE }}
