export const ACCOUNT_HAS_NO_ACCRUED_INTEREST = 133;
export const ACCOUNT_NOT_ACTIVE = 3820;

export const INTEREST_ERROR_CODES_ALLOWED = [
  ACCOUNT_HAS_NO_ACCRUED_INTEREST,
  ACCOUNT_NOT_ACTIVE,
];

export enum AccountsProcess {
  JUDICIAL_RETENTION_PROCESS = 'RETENCION_JUDICIAL',
}
