export const ErrorCodes = {
  // Authentication Errors (000-099)
  AUTH_TOKEN_INVALID: 'NB_ERR_001',
  AUTH_SESSION_EXPIRED: 'NB_ERR_002',
  AUTH_OTP_INVALID: 'NB_ERR_003',
  AUTH_OTP_EXPIRED: 'NB_ERR_004',
  AUTH_USER_NOT_FOUND: 'NB_ERR_005',

  // OTP Validation Errors (006-008)
  AUTH_OTP_VALIDATION_FAILED: 'NB_ERR_006',
  AUTH_OTP_REQUEST_INVALID: 'NB_ERR_007',
  AUTH_OTP_UPDATE_FAILED: 'NB_ERR_008',

  // Onboarding Errors (100-199)
  ONB_STATUS_INVALID: 'NB_ERR_101',
  ONB_STEP_INVALID: 'NB_ERR_102',
  ONB_GET_SESSION_FAIL: 'NB_ERR_103',
  ONB_DATA_INCOMPLETE: 'NB_ERR_104',
  ONB_FLOW_BLOCKED: 'NB_ERR_105',
  ONB_STATUS_NOT_FOUND: 'NB_ERR_106',
  ONB_SESSION_INVALID: 'NB_ERR_107',
  ONB_VALIDATE_IDENTITY_ID_FAILED: 'NB_ERR_108',
  ONB_VALIDATE_DOCUMENT_ID_PENDING: 'NB_ERR_109',
  ONB_SERVICE_ERROR: 'NB_ERR_110',
  ONB_UPDATE_SESSION_FAIL: 'NB_ERR_111',
  ONB_BLOCKED_PERMANENTLY: 'NB_ERR_112',

  // Client Errors (200-299)
  CLIENT_ID_INVALID: 'NB_ERR_201',
  CLIENT_STATUS_INVALID: 'NB_ERR_202',
  CLIENT_DATA_MISSING: 'NB_ERR_203',
  CLIENT_TYPE_INVALID: 'NB_ERR_204',
  CLIENT_UPDATE_FAILED: 'NB_ERR_205',
  CLIENT_BLOCKED_TMP_OTP: 'NB_ERR_206',

  // Document Errors (300-399)
  DOC_FORMAT_INVALID: 'NB_ERR_301',
  DOC_SIZE_EXCEEDED: 'NB_ERR_302',
  DOC_TYPE_INVALID: 'NB_ERR_303',
  DOC_UPLOAD_FAILED: 'NB_ERR_304',
  DOC_SIGN_FAILED: 'NB_ERR_305',
  DOC_RESPONSE_INVALID: 'NB_ERR_306',

  // Contract Errors (400-499)
  CONTRACT_SIGN_PENDING: 'NB_ERR_401',
  CONTRACT_SIGN_EXPIRED: 'NB_ERR_402',
  CONTRACT_DATA_INVALID: 'NB_ERR_403',
  CONTRACT_TYPE_INVALID: 'NB_ERR_404',
  CONTRACT_STATUS_INVALID: 'NB_ERR_405',
  CONTRACT_SIGN_FAILED: 'NB_ERR_406',
  CONTRACT_PROCESS_FAILED: 'NB_ERR_407',

  // Billing Errors (500-599)
  BILL_AMOUNT_INVALID: 'NB_ERR_501',
  BILL_ACCOUNT_INVALID: 'NB_ERR_502',
  BILL_STATUS_FAILED: 'NB_ERR_503',
  BILL_DATA_MISSING: 'NB_ERR_504',
  BILL_PROCESS_FAILED: 'NB_ERR_505',

  // Notification Errors (600-699)
  NOTIF_SEND_FAILED: 'NB_ERR_601',
  NOTIF_TYPE_INVALID: 'NB_ERR_602',
  NOTIF_DATA_MISSING: 'NB_ERR_603',
  NOTIF_TEMPLATE_INVALID: 'NB_ERR_604',
  NOTIF_CHANNEL_INVALID: 'NB_ERR_605',

  // File Upload Errors (700-799)
  FILE_UPLOAD_INVALID_TYPE: 'NB_ERR_701',
  FILE_UPLOAD_EMPTY: 'NB_ERR_702',
  FILE_UPLOAD_PROCESSING_ERROR: 'NB_ERR_703',
  FILE_UPLOAD_SIZE_EXCEEDED: 'NB_ERR_704',
  FILE_UPLOAD_STREAM_ERROR: 'NB_ERR_705',
  FILE_UPLOAD_INVALID_FORMAT: 'NB_ERR_706',
  FILE_UPLOAD_NO_CONTENT: 'NB_ERR_707',
  FILE_UPLOAD_SERVICE_ERROR: 'NB_ERR_708',

  // CNB Errors (800-899)
  CNB_USER_NOT_FOUND: 'NB_ERR_801',
  CNB_CLIENT_NOT_FOUND: 'NB_ERR_802',
  CNB_NOT_PRECALIFIED: 'NB_ERR_803',
  CNB_INVALID_STATUS: 'NB_ERR_804',
  CNB_SERVICE_ERROR: 'NB_ERR_805',
  CNB_CLIENT_INVALID_ADDRESS: 'NB_ERR_806',
  CNB_CONFIG_ADDRESS_ERROR: 'NB_ERR_807',

  // System Errors (900-999)
  SYS_SERVICE_DOWN: 'NB_ERR_901',
  SYS_TIMEOUT_EXCEEDED: 'NB_ERR_902',
  SYS_PROCESS_FAILED: 'NB_ERR_903',
  SYS_CONFIG_INVALID: 'NB_ERR_904',
  SYS_ERROR_UNKNOWN: 'NB_ERR_905',

  // General Field Validation Errors (9000–9099)
  VALIDATION_FIELD_REQUIRED: 'NB_ERR_9011',
  VALIDATION_FIELD_INVALID_NUMBER: 'NB_ERR_9012',
  VALIDATION_FIELD_MIN_VALUE: 'NB_ERR_9013',
  VALIDATION_FIELD_MAX_VALUE: 'NB_ERR_9014',
  MONTH_FORMAT_INVALID: 'NB_ERR_9015',
  MONTH_RANGE_INVALID: 'NB_ERR_9016',
  END_MONTH_CANNOT_BE_FUTURE: 'NB_ERR_9017',

  // Calification Errors (1000-1099)
  CALIFICATION_INVALID_RATING: 'NB_ERR_1001',
  CALIFICATION_INVALID_USER: 'NB_ERR_1002',
  CALIFICATION_INVALID_CONTEXT: 'NB_ERR_1003',
  CALIFICATION_SERVICE_ERROR: 'NB_ERR_1004',
  CALIFICATION_PROCESS_FAILED: 'NB_ERR_1005',

  // Transaction Errors (1100-1199)
  TRANSACTION_AMOUNT_INVALID: 'NB_ERR_1101',
  TRANSACTION_ID_INVALID: 'NB_ERR_1102',
  TRANSACTION_SESSION_INVALID: 'NB_ERR_1103',
  TRANSACTION_DEVICE_INVALID: 'NB_ERR_1104',
  TRANSACTION_USER_INVALID: 'NB_ERR_1105',
  TRANSACTION_LIMIT_EXCEEDED: 'NB_ERR_1106',
  TRANSACTION_SERVICE_ERROR: 'NB_ERR_1107',
  TRANSACTION_STATUS_INVALID: 'NB_ERR_1108',
  TRANSACTION_PROCESS_FAILED: 'NB_ERR_1109',
  BANK_NAME_INVALID: 'NB_ERR_1110',
  INITIATE_CELLPHONE_DEPOSIT_FAILED: 'NB_ERR_1111',
  TRANSACTION_USER_DATA_NOT_FOUND: 'NB_ERR_1112',
  INITIATE_CONFIRM_DEPOSIT_FAILED: 'NB_ERR_1113',
  VALIDATE_DEPOSIT_ACCOUNT_FAILED: 'NB_ERR_1114',

  // ID Document Validation Errors (1200-1299)
  ID_DOC_TYPE_INVALID: 'NB_ERR_1201',
  ID_DOC_NUMBER_INVALID: 'NB_ERR_1202',
  ID_DOC_EXPIRED: 'NB_ERR_1203',
  ID_DOC_NOT_FOUND: 'NB_ERR_1204',
  ID_DOC_FORMAT_INVALID: 'NB_ERR_1205',
  ID_DOC_VERIFICATION_FAILED: 'NB_ERR_1206',
  ID_DOC_STATUS_INVALID: 'NB_ERR_1207',
  ID_DOC_PROCESS_FAILED: 'NB_ERR_1208',
  ID_DOC_SERVICE_ERROR: 'NB_ERR_1209',

  // KYC Validation Errors (1300-1399)
  KYC_VALIDATION_FAILED: 'NB_ERR_1301',
  KYC_VALIDATION_SERVICE_ERROR: 'NB_ERR_1302',
  KYC_VALIDATION_PROCESS_FAILED: 'NB_ERR_1303',
  KYC_VALIDATION_STATUS_INVALID: 'NB_ERR_1304',
  KYC_VALIDATION_DATA_MISSING: 'NB_ERR_1305',
  KYC_VALIDATION_DATA_INVALID: 'NB_ERR_1306',
  KYC_VALIDATION_DOCUMENT_ERROR: 'NB_ERR_1307',

  // Qr Errors (1400-1499)
  MERCHANT_CLIENT_INFO_INVALID: 'NB_ERR_1401',

  // Morphology Validation Errors (1500-1599)
  MORPHOLOGY_VALIDATION_FAILED: 'NB_ERR_1501',
  MORPHOLOGY_SERVICE_ERROR: 'NB_ERR_1502',
  MORPHOLOGY_FACIAL_VALIDATION_FAILED: 'NB_ERR_1503',
  MORPHOLOGY_LIVENESS_VALIDATION_FAILED: 'NB_ERR_1504',
  MORPHOLOGY_DATA_INVALID: 'NB_ERR_1505',
  MORPHOLOGY_REQUEST_TIMEOUT: 'NB_ERR_1506',
  MORPHOLOGY_PROCESS_FAILED: 'NB_ERR_1507',

  // Document Validation Errors (1600-1699)
  DOCUMENT_VALIDATION_FAILED: 'NB_ERR_1601',
  DOCUMENT_VALIDATION_SERVICE_ERROR: 'NB_ERR_1602',
  DOCUMENT_VALIDATION_DATA_INVALID: 'NB_ERR_1603',
  DOCUMENT_VALIDATION_REQUEST_TIMEOUT: 'NB_ERR_1604',
  DOCUMENT_VALIDATION_PROCESS_FAILED: 'NB_ERR_1605',
  DOCUMENT_VALIDATION_CNB_ORQ_DOCUMENT_ERROR: 'NB_ERR_1606',

  // Template Generator Errors (1700-1799)
  TL_TEMPLATE_GENERATION_FAIL: 'NB_ERR_1701',

  // Electronic Signature Errors (1800-1899)
  DOCUMENT_ELECTRONIC_SIGNATURE_FAILED: 'NB_ERR_1801',
  DOCUMENT_ELECTRONIC_SIGNATURE_SERVICE_ERROR: 'NB_ERR_1802',
  DOCUMENT_ELECTRONIC_SIGNATURE_PROCESS_FAILED: 'NB_ERR_1803',
  DOCUMENT_ELECTRONIC_SIGNATURE_REQUEST_TIMEOUT: 'NB_ERR_1804',
  DOCUMENT_ELECTRONIC_SIGNATURE_DATA_INVALID: 'NB_ERR_1805',

  // Decryption Errors (1800-1899)
  DECRYPTION_FIELD_FAILED: 'NB_ERR_1901',
  DECRYPTION_ERROR_GENERIC: 'NB_ERR_1902',

  // redis errors (2000-2099)
  REDIS_SAVE_ERROR: 'NB_ERR_2001',
  REDIS_GET_ERROR: 'NB_ERR_2002',
  REDIS_DELETE_ERROR: 'NB_ERR_2003',
  REDIS_UPDATE_ERROR: 'NB_ERR_2004',
  REDIS_EXISTS_ERROR: 'NB_ERR_2005',
  REDIS_EXPIRE_ERROR: 'NB_ERR_2006',
  REDIS_SCAN_ERROR: 'NB_ERR_2007',

  // fingerprint errors (2100-2199)
  FINGERPRINT_ERROR: 'NB_ERR_2101',

  // Opensearch Errors (2200-2299)
  TL_OPENSEARCH_ERROR: 'NB_ERR_2201',

  // BpDataProvider Errors (2300-2399)
  TL_BP_DATA_PROVIDER_ERROR: 'NB_ERR_2301',

  // MsaCrCommissionsService Errors (2400-2499)
  MSA_CR_COMMISSIONS_SERVICE_ERROR: 'NB_ERR_2401',

  // MsaTlDigisignInvoiceService Errors (2500-2599)
  MSA_TL_DIGISIGN_INVOICE_SERVICE_ERROR: 'NB_ERR_2501',
  MSA_TL_DIGISIGN_INVOICE_RUC_INFORMATION_NOT_FOUND: 'NB_ERR_2502',
  MSA_TL_DIGISIGN_INVOICE_CREATE_INVOICE_ERROR: 'NB_ERR_2503',
};
