export const ErrorCodes = {
  // Authentication Errors (000-099)
  AUTH_TOKEN_INVALID: 'NB_ERR_001',
  AUTH_SESSION_EXPIRED: 'NB_ERR_002',
  AUTH_OTP_INVALID: 'NB_ERR_003',
  AUTH_OTP_EXPIRED: 'NB_ERR_004',
  AUTH_USER_NOT_FOUND: 'NB_ERR_005',

  // Onboarding Errors (100-199)
  ONB_STATUS_INVALID: 'NB_ERR_101',
  ONB_STEP_INVALID: 'NB_ERR_102',
  ONB_SESSION_EXPIRED: 'NB_ERR_103',
  ONB_DATA_INCOMPLETE: 'NB_ERR_104',
  ONB_FLOW_BLOCKED: 'NB_ERR_105',

  // Client Errors (200-299)
  CLIENT_ID_INVALID: 'NB_ERR_201',
  CLIENT_STATUS_INVALID: 'NB_ERR_202',
  CLIENT_DATA_MISSING: 'NB_ERR_203',
  CLIENT_TYPE_INVALID: 'NB_ERR_204',
  CLIENT_UPDATE_FAILED: 'NB_ERR_205',

  // Document Errors (300-399)
  DOC_FORMAT_INVALID: 'NB_ERR_301',
  DOC_SIZE_EXCEEDED: 'NB_ERR_302',
  DOC_TYPE_INVALID: 'NB_ERR_303',
  DOC_UPLOAD_FAILED: 'NB_ERR_304',
  DOC_SIGN_FAILED: 'NB_ERR_305',

  // Contract Errors (400-499)
  CONTRACT_SIGN_PENDING: 'NB_ERR_401',
  CONTRACT_SIGN_EXPIRED: 'NB_ERR_402',
  CONTRACT_DATA_INVALID: 'NB_ERR_403',
  CONTRACT_TYPE_INVALID: 'NB_ERR_404',
  CONTRACT_STATUS_INVALID: 'NB_ERR_405',

  // Billing Errors (500-599)
  BILL_AMOUNT_INVALID: 'NB_ERR_501',
  BILL_ACCOUNT_INVALID: 'NB_ERR_502',
  BILL_STATUS_FAILED: 'NB_ERR_503',
  BILL_DATA_MISSING: 'NB_ERR_504',
  BILL_PROCESS_FAILED: 'NB_ERR_505',

  // Notification Errors (600-699)
  NOTIF_SEND_FAILED: 'NB_ERR_601',
  NOTIF_TYPE_INVALID: 'NB_ERR_602',
  NOTIF_DATA_MISSING: 'NB_ERR_603',
  NOTIF_TEMPLATE_INVALID: 'NB_ERR_604',
  NOTIF_CHANNEL_INVALID: 'NB_ERR_605',

  // System Errors (900-999)
  SYS_SERVICE_DOWN: 'NB_ERR_901',
  SYS_TIMEOUT_EXCEEDED: 'NB_ERR_902',
  SYS_PROCESS_FAILED: 'NB_ERR_903',
  SYS_CONFIG_INVALID: 'NB_ERR_904',
  SYS_ERROR_UNKNOWN: 'NB_ERR_905',
};
