export const TAX_REGIMES = {
  GENERAL: 'RÉGIMEN GENERAL',
  RIMPE_ENTREPRENEUR: 'RÉGIMEN RIMPE - EMPRENDEDOR',
  RIMPE_POPULAR_BUSINESS: 'RÉGIMEN RIMPE - NEGOCIO POPULAR',
  SPECIAL_TAXPAYER: 'CONTRIBUYENTE ESPECIAL',
};

export const VAT_RATES = {
  [TAX_REGIMES.GENERAL]: 0.15,
  [TAX_REGIMES.RIMPE_ENTREPRENEUR]: 0.15,
  [TAX_REGIMES.RIMPE_POPULAR_BUSINESS]: 0.0,
  [TAX_REGIMES.SPECIAL_TAXPAYER]: 0.15,
};
