// Application Ports
export const PRODUCT_VALIDATION_PORT = 'PRODUCT_VALIDATION_PORT';
export const PRODUCT_VALIDATION_SERVICE_PORT =
  'PRODUCT_VALIDATION_SERVICE_PORT';

// Infrastructure Ports
export const MAMBU_CLIENT_PORT = 'MAMBU_CLIENT_PORT';
